language: python
cache: pip
python:
  - "2.7.10"
  - "2.7.12"
  - "3.5"
  - "3.6"
install:
  - python setup.py install
  - pip install pexpect
script:
  - python kubeshell/tests/test_cli.py
sudo: false
